# Generated by Django 2.2.1 on 2019-05-16 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0012_auto_20190516_0635'),
        ('base', '0003_auto_20190515_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbasecoupon',
            name='bar',
            field=models.ForeignKey(blank=True, help_text='Select bar if this coupon is restricted to particular bar', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='bar.ModelBar', verbose_name='Bar'),
        ),
        migrations.AlterField(
            model_name='modelbasecoupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
