# Generated by Django 2.2.1 on 2019-05-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190516_0635'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelbasecouponuser',
            unique_together=set(),
        ),
    ]
