# Generated by Django 2.2.1 on 2019-05-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190523_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbasecoupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
