# Generated by Django 2.2.1 on 2019-05-07 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bar.', max_length=500)),
                ('address', models.TextField()),
                ('latitude', models.CharField(blank=True, help_text='Latitude of bar address', max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, help_text='Longitude of bar address', max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner', models.ForeignKey(help_text='Owner of the bar.', on_delete=django.db.models.deletion.CASCADE, related_name='bars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bar',
                'verbose_name_plural': 'Bars',
                'db_table': 'bar',
            },
        ),
        migrations.CreateModel(
            name='ModelBarTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(help_text='Day when open the bar.', max_length=100)),
                ('start_time', models.CharField(blank=True, help_text='Timing of opening the bar.', max_length=100, null=True)),
                ('end_time', models.CharField(blank=True, help_text='Timing of closing the bar.', max_length=100, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='bar.ModelBar')),
            ],
            options={
                'verbose_name': 'Bar Timing',
                'verbose_name_plural': 'Bar Timings',
                'db_table': 'bar_timing',
            },
        ),
    ]
