# Generated by Django 2.2.1 on 2019-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbar',
            name='logo',
            field=models.ImageField(default='', upload_to='', verbose_name=models.ImageField(blank=True, help_text='Logo of the bar', null=True, upload_to='bar/')),
            preserve_default=False,
        ),
    ]
