# Generated by Django 2.2.1 on 2019-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_auto_20190508_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBarCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category', max_length=200)),
            ],
            options={
                'verbose_name': 'Bar Category',
                'verbose_name_plural': 'Bar Categories',
                'db_table': 'bar_category',
            },
        ),
    ]
