# Generated by Django 2.2.1 on 2019-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_modelbar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbarcategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='Logo of the bar', null=True, upload_to='bar/category/'),
        ),
    ]
