# Generated by Django 2.2.1 on 2019-05-09 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bar', '0006_modelbarcategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBarProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Product', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Logo of the bar', null=True, upload_to='bar/product/')),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bar.ModelBar')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'bar_product',
            },
        ),
        migrations.CreateModel(
            name='ModelBarProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_rating', models.PositiveIntegerField(blank=True, help_text='The rating of particular bar', null=True)),
                ('product_rating', models.PositiveIntegerField(blank=True, help_text='The rating of particular product', null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bar.ModelBarProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'bar_product_rating',
            },
        ),
    ]
