# Generated by Django 2.2.1 on 2019-05-10 07:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bar', '0007_modelbarproduct_modelbarproductrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBarPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('title', models.CharField(help_text='Title of the plan', max_length=255)),
                ('price', models.PositiveIntegerField(help_text='Price of the plan')),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in months only')),
                ('is_active', models.BooleanField(default=True, help_text='Admin toggle to display/hide the plan from the user')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'bar_plan',
            },
        ),
        migrations.AddField(
            model_name='modelbar',
            name='country',
            field=models.ForeignKey(help_text='Country of the bar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bars', to='base.ModelBaseCountry'),
        ),
        migrations.AddField(
            model_name='modelbarproductrating',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time when this entry was created in the system'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelbarproductrating',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system'),
        ),
        migrations.AlterField(
            model_name='modelbar',
            name='latitude',
            field=models.CharField(default='', help_text='Latitude of bar address', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelbar',
            name='longitude',
            field=models.CharField(default='', help_text='Longitude of bar address', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelbartiming',
            name='day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day when open the bar.', max_length=100),
        ),
        migrations.CreateModel(
            name='ModelBarSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('expiration', models.DateTimeField()),
                ('transaction_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='bar.ModelBarPlan')),
                ('user', models.OneToOneField(help_text='User related to subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'bar_subscription',
            },
        ),
    ]
