# Generated by Django 2.2.1 on 2019-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_auto_20190510_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbarplan',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], default='', help_text='In which currency you want to pay.', max_length=20),
            preserve_default=False,
        ),
    ]
