# Generated by Django 2.2.1 on 2019-05-16 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190516_0635'),
        ('bar', '0012_auto_20190516_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbarsubscription',
            name='active',
            field=models.BooleanField(default=False, help_text='The active subscription of the user'),
        ),
        migrations.AddField(
            model_name='modelbarsubscription',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Coupon attached to the subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ModelBaseCoupon'),
        ),
        migrations.AlterField(
            model_name='modelbarsubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='bar.ModelBarPlan'),
        ),
        migrations.AlterField(
            model_name='modelbarsubscription',
            name='user',
            field=models.ForeignKey(help_text='User related to subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
