# Generated by Django 2.2.1 on 2019-05-21 09:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0013_auto_20190516_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbar',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
