# Generated by Django 2.2.1 on 2019-05-21 12:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0016_auto_20190521_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbar',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
