# Generated by Django 2.2.1 on 2019-05-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0017_auto_20190521_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbartiming',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day when open the bar.', max_length=100),
        ),
    ]
