# Generated by Django 2.2.1 on 2019-05-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0018_auto_20190527_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelbarproduct',
            name='bar',
        ),
        migrations.AddField(
            model_name='modelbar',
            name='drinks',
            field=models.ManyToManyField(blank=True, related_name='bars', to='bar.ModelBarProduct'),
        ),
    ]
