# Generated by Django 2.2.1 on 2019-05-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0020_modelbarproduct_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbarplan',
            name='price',
            field=models.FloatField(help_text="Specify one time price of the price (per interval). If plan is monthly provide 1 month price, if it's yearly provide 1 year or 12 month price"),
        ),
    ]
