# Generated by Django 2.2.1 on 2019-06-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0023_auto_20190529_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelbar',
            name='category',
        ),
        migrations.AddField(
            model_name='modelbar',
            name='bar_category',
            field=models.ManyToManyField(related_name='bars', to='bar.ModelBarCategory'),
        ),
    ]
