# Generated by Django 2.2.1 on 2019-06-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0024_auto_20190614_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbar',
            name='bar_photography',
            field=models.ImageField(blank=True, help_text='Logo of the bar', null=True, upload_to='bar/photography/'),
        ),
    ]
