# Generated by Django 2.2.1 on 2019-06-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0025_modelbar_bar_photography'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbarorder',
            name='bar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bar.ModelBar'),
            preserve_default=False,
        ),
    ]
