# Generated by Django 2.2.1 on 2019-06-24 10:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0026_modelbarorder_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbar',
            name='bar_timings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
