# Generated by Django 2.2.1 on 2019-06-27 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0027_modelbar_bar_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbarsubscription',
            name='user',
            field=models.ForeignKey(help_text='User related to subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
