# Generated by Django 2.2.1 on 2019-06-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0028_auto_20190627_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbar',
            name='publish',
            field=models.BooleanField(default=False, help_text='Show the bar on app according to publish status'),
        ),
    ]
