# Generated by Django 2.2.1 on 2019-07-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0029_modelbar_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbarproduct',
            name='is_default',
            field=models.BooleanField(default=False, help_text='show products which are deafult show to every user'),
        ),
    ]
